version: '3.8'
services:
  simpe-web-service:
    image: devopsdockeruh/simple-web-service:alpine
    build: .
    volumes:
      - ./text.log:/usr/src/app/text.log
    container_name: simple-web-service