FROM node:16 as base

WORKDIR /usr/src/app

COPY . .

RUN npm install
ENV REACT_APP_BACKEND_URL=http://localhost:8080

RUN npm run build
RUN npm install -g serve
ENTRYPOINT [ "serve", "-s", "-l", "8000", "build" ]
