version: '3.8'
services:
  backend:
    image: goappp
    container_name: example-backend
    ports:
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=http://localhost:8000
  frontend:
    image: front-app
    container_name: example-frontend
    ports:
      - 8000:8000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080